name: linguaml
channels:
  - conda-forge
  - defaults
dependencies:
  - accessible-pygments=0.0.4
  - alabaster=0.7.13
  - appnope=0.1.3
  - asttokens=2.4.0
  - attrs=23.1.0
  - babel=2.12.1
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.5
  - beautifulsoup4=4.12.2
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - ca-certificates=2023.7.22
  - certifi=2023.7.22
  - charset-normalizer=3.2.0
  - click=8.1.7
  - colorama=0.4.6
  - comm=0.1.4
  - dataclasses=0.8
  - debugpy=1.7.0
  - docutils=0.18.1
  - exceptiongroup=1.1.3
  - executing=1.2.0
  - greenlet=2.0.2
  - idna=3.4
  - imagesize=1.4.1
  - importlib-metadata=6.8.0
  - importlib_metadata=6.8.0
  - importlib_resources=6.0.1
  - ipykernel=6.25.2
  - ipython=8.15.0
  - jedi=0.19.0
  - jinja2=3.1.2
  - jsonschema=4.19.0
  - jsonschema-specifications=2023.7.1
  - jupyter-book=0.15.1
  - jupyter-cache=0.6.1
  - jupyter_client=8.3.1
  - jupyter_core=5.3.1
  - latexcodec=2.0.1
  - libcxx=16.0.6
  - libffi=3.4.4
  - libsodium=1.0.18
  - linkify-it-py=2.0.0
  - markdown-it-py=2.2.0
  - markupsafe=2.1.3
  - matplotlib-inline=0.1.6
  - mdit-py-plugins=0.4.0
  - mdurl=0.1.0
  - myst-nb=0.17.2
  - myst-parser=0.18.1
  - nbclient=0.7.4
  - nbformat=5.9.2
  - ncurses=6.4
  - nest-asyncio=1.5.6
  - openssl=3.1.2
  - packaging=23.1
  - parso=0.8.3
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=23.2.1
  - pkgutil-resolve-name=1.3.10
  - platformdirs=3.10.0
  - prompt-toolkit=3.0.39
  - prompt_toolkit=3.0.39
  - psutil=5.9.5
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pybtex=0.24.0
  - pybtex-docutils=1.0.3
  - pydata-sphinx-theme=0.13.3
  - pygments=2.16.1
  - pysocks=1.7.1
  - python=3.11.4
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.18.0
  - python_abi=3.11
  - pytz=2023.3.post1
  - pyyaml=6.0.1
  - pyzmq=25.1.1
  - readline=8.2
  - referencing=0.30.2
  - requests=2.31.0
  - rpds-py=0.10.2
  - setuptools=68.0.0
  - six=1.16.0
  - snowballstemmer=2.2.0
  - soupsieve=2.5
  - sphinx=5.0.2
  - sphinx-book-theme=1.0.1
  - sphinx-comments=0.0.3
  - sphinx-copybutton=0.5.2
  - sphinx-design=0.3.0
  - sphinx-external-toc=0.3.1
  - sphinx-jupyterbook-latex=0.5.2
  - sphinx-multitoc-numbering=0.1.3
  - sphinx-thebe=0.2.1
  - sphinx-togglebutton=0.3.2
  - sphinxcontrib-applehelp=1.0.7
  - sphinxcontrib-bibtex=2.5.0
  - sphinxcontrib-devhelp=1.0.5
  - sphinxcontrib-htmlhelp=2.0.4
  - sphinxcontrib-jsmath=1.0.1
  - sphinxcontrib-qthelp=1.0.6
  - sphinxcontrib-serializinghtml=1.1.9
  - sqlalchemy=2.0.20
  - sqlite=3.41.2
  - stack_data=0.6.2
  - tabulate=0.9.0
  - tk=8.6.12
  - tornado=6.3.3
  - traitlets=5.9.0
  - typing-extensions=4.7.1
  - typing_extensions=4.7.1
  - uc-micro-py=1.0.1
  - wcwidth=0.2.6
  - wheel=0.38.4
  - xz=5.4.2
  - yaml=0.2.5
  - zeromq=4.3.4
  - zipp=3.16.2
  - zlib=1.2.13
  - pip:
    - aiohttp==3.8.5
    - aiohttp-cors==0.7.0
    - aiosignal==1.3.1
    - async-timeout==4.0.3
    - blessed==1.20.0
    - build==1.0.3
    - cachetools==5.3.1
    - cloudpickle==2.2.1
    - colorful==0.5.5
    - contourpy==1.1.0
    - cycler==0.11.0
    - decorator==4.4.2
    - distlib==0.3.7
    - farama-notifications==0.0.4
    - filelock==3.12.3
    - fonttools==4.42.1
    - frozenlist==1.4.0
    - ghp-import==2.1.0
    - google-api-core==2.11.1
    - google-auth==2.23.0
    - googleapis-common-protos==1.60.0
    - gpustat==1.1.1
    - grpcio==1.58.0
    - gym==0.26.2
    - gym-notices==0.0.8
    - gymnasium==0.29.1
    - imageio==2.31.3
    - imageio-ffmpeg==0.4.9
    - jaraco-classes==3.3.0
    - joblib==1.3.2
    - keyring==24.2.0
    - kiwisolver==1.4.5
    - lz4==4.3.2
    - matplotlib==3.7.2
    - more-itertools==10.1.0
    - moviepy==1.0.3
    - mpmath==1.3.0
    - msgpack==1.0.5
    - multidict==6.0.4
    - networkx==3.1
    - nh3==0.2.14
    - numpy==1.25.2
    - nvidia-ml-py==12.535.108
    - opencensus==0.11.2
    - opencensus-context==0.1.3
    - pandas==2.1.0
    - pillow==10.0.0
    - pkginfo==1.9.6
    - proglog==0.1.10
    - prometheus-client==0.17.1
    - protobuf==4.24.3
    - py-spy==0.3.14
    - pyasn1==0.5.0
    - pyasn1-modules==0.3.0
    - pydantic==1.10.12
    - pygame==2.5.1
    - pyparsing==3.0.9
    - pyproject-hooks==1.0.0
    - ray==2.6.3
    - readme-renderer==42.0
    - requests-toolbelt==1.0.0
    - rfc3986==2.0.0
    - rich==13.5.2
    - rsa==4.9
    - scikit-learn==1.3.0
    - scipy==1.11.2
    - smart-open==6.4.0
    - stable-baselines3==2.1.0
    - sympy==1.12
    - threadpoolctl==3.2.0
    - torch==2.0.1
    - torchaudio==2.0.2
    - torchvision==0.15.2
    - tqdm==4.66.1
    - twine==4.0.2
    - tzdata==2023.3
    - urllib3==1.26.16
    - virtualenv==20.21.0
    - yarl==1.9.2
